# Generated by Django 4.2.5 on 2023-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
