# Generated by Django 4.2.5 on 2023-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_notification_task_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
