# Generated by Django 4.2.5 on 2023-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='tg_username',
        ),
        migrations.AddField(
            model_name='telegram',
            name='tg_chat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='telegram',
            name='tg_random_salt',
            field=models.CharField(null=True),
        ),
    ]
