# Generated by Django 4.2.5 on 2023-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_telegram_tg_username_telegram_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='tg_chat_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='tg_random_salt',
            field=models.CharField(default=None, null=True),
        ),
    ]
